Update sonar.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -27,3 +27,16 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Check Quality Gate Status
+        run: |
+          quality_gate_status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=dmaity2511_sonarclouddemo")
+          status=$(echo "$quality_gate_status" | jq -r .projectStatus.status)
+          if [[ "$status" != "OK" ]]; then
+            echo "Quality gate check failed: $status"
+            exit 1
+          else
+            echo "Quality gate check passed"
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
