Update sonar.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -1,8 +1,7 @@
 name: Sonar Cloud Analysis
 
 on:
-  # Trigger analysis when pushing in master or pull requests, and when creating
-  # a pull request.
+  # Trigger analysis when pushing to the 'sonarcloud' branch, and when creating or updating pull requests.
   workflow_dispatch:
   push:
     branches:
@@ -22,10 +21,29 @@ jobs:
         with:
           # Shallow clones should be disabled for a better relevancy of analysis
           fetch-depth: 0
-      - name: Scan
+      - name: Run SonarCloud Analysis
         uses: SonarSource/sonarcloud-github-action@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
+  quality_gate_check:
+    name: Quality Gate Check
+    needs: sonarcloud
+    runs-on: ubuntu-latest
+    steps:
+      - name: Wait for Analysis to Complete
+        run: sleep 60 # Wait for 1 minute
+      - name: Check Quality Gate Status
+        run: |
+          quality_gate_status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=dmaity2511_sonarclouddemo")
+          status=$(echo "$quality_gate_status" | jq -r .projectStatus.status)
+          if [[ "$status" != "OK" ]]; then
+            echo "Quality gate check failed: $status"
+            exit 1
+          else
+            echo "Quality gate check passed"
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
